-- +goose Up
CREATE TABLE media_asset (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            varchar(128)  NOT NULL DEFAULT '',
    cover_url        varchar(512)  NOT NULL DEFAULT '',
    source_bucket    varchar(128)  NOT NULL DEFAULT '',
    source_key       varchar(512)  NOT NULL DEFAULT '',
    play_key         varchar(512)  NOT NULL DEFAULT '',
    play_url         varchar(1024) NOT NULL DEFAULT '',
    duration_sec     int           NOT NULL DEFAULT 0,
    status           smallint      NOT NULL DEFAULT 0,  -- 0草稿 1转码中 2就绪 3失败 4下架
    transcode_status varchar(16)   NOT NULL DEFAULT 'none', -- none|pending|processing|ready|failed
    transcode_job_id varchar(64)   NOT NULL DEFAULT '',
    transcode_error  text          NOT NULL DEFAULT '',
    remark           varchar(255)  NOT NULL DEFAULT '',
    created_at       timestamptz   NOT NULL DEFAULT now(),
    updated_at       timestamptz   NOT NULL DEFAULT now()
);

CREATE INDEX idx_media_asset_status ON media_asset (status);
CREATE INDEX idx_media_asset_created ON media_asset (created_at DESC);
COMMENT ON TABLE media_asset IS '中央媒资池资产';

-- +goose Down
DROP TABLE IF EXISTS media_asset;
