-- +goose Up
CREATE TABLE transcode_job (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      varchar(64)  NOT NULL,
    asset_id    bigint       NOT NULL,
    profile     varchar(32)  NOT NULL DEFAULT 'h264_hls',
    status      varchar(16)  NOT NULL DEFAULT 'pending', -- pending|processing|ready|failed
    error       text         NOT NULL DEFAULT '',
    play_key    varchar(512) NOT NULL DEFAULT '',
    play_url    varchar(1024) NOT NULL DEFAULT '',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    finished_at timestamptz
);

CREATE UNIQUE INDEX uk_transcode_job_id ON transcode_job (job_id);
CREATE INDEX idx_transcode_job_asset ON transcode_job (asset_id);
COMMENT ON TABLE transcode_job IS '转码任务轨迹(Kafka job_id)';

-- +goose Down
DROP TABLE IF EXISTS transcode_job;
