-- +goose Up
CREATE TABLE paas_client (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_key    varchar(64)  NOT NULL,
    app_secret varchar(128) NOT NULL DEFAULT '', -- 骨架明文; 后续改哈希或对接总后台校验
    site_code  varchar(32)  NOT NULL DEFAULT '',
    status     smallint     NOT NULL DEFAULT 1,  -- 1启用 0停用
    remark     varchar(255) NOT NULL DEFAULT '',
    created_at timestamptz  NOT NULL DEFAULT now(),
    updated_at timestamptz  NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_paas_client_app_key ON paas_client (app_key);
COMMENT ON TABLE paas_client IS '开放API调用方(站点凭证镜像)';

CREATE TABLE site_asset_pick (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app_key    varchar(64) NOT NULL,
    site_code  varchar(32) NOT NULL DEFAULT '',
    asset_id   bigint      NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX uk_site_asset_pick ON site_asset_pick (app_key, asset_id);
CREATE INDEX idx_site_asset_pick_asset ON site_asset_pick (asset_id);
COMMENT ON TABLE site_asset_pick IS '子站选用记录(审计)';

-- +goose Down
DROP TABLE IF EXISTS site_asset_pick;
DROP TABLE IF EXISTS paas_client;
