-- 媒资增加漫画类型: kind=0 视频(默认) kind=1 漫画。章节页图索引单独成表。
-- +goose Up
ALTER TABLE media_asset
    ADD COLUMN IF NOT EXISTS kind smallint NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS category varchar(64) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS intro varchar(2000) NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS chapter_count int NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_media_asset_kind ON media_asset (kind, status, created_at DESC);
COMMENT ON COLUMN media_asset.kind IS '0视频 1漫画';

CREATE TABLE IF NOT EXISTS media_comic_chapter (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asset_id    bigint       NOT NULL,
    seq         int          NOT NULL,
    title       varchar(128) NOT NULL DEFAULT '',
    page_count  int          NOT NULL DEFAULT 0,
    pages       jsonb        NOT NULL DEFAULT '[]',
    created_at  timestamptz  NOT NULL DEFAULT now(),
    UNIQUE (asset_id, seq)
);
CREATE INDEX IF NOT EXISTS idx_media_comic_chapter_asset ON media_comic_chapter (asset_id, seq);
COMMENT ON TABLE media_comic_chapter IS '媒资漫画章节(pages=[{key,filename}])';

-- +goose Down
DROP TABLE IF EXISTS media_comic_chapter;
ALTER TABLE media_asset
    DROP COLUMN IF EXISTS kind,
    DROP COLUMN IF EXISTS category,
    DROP COLUMN IF EXISTS intro,
    DROP COLUMN IF EXISTS chapter_count;
